import React from 'react';
import { Link } from 'react-router-dom';

export default function Privacy() {
  return (
    <main className="max-w-2xl mx-auto px-4 py-10">
      <Link to="/" className="inline-flex items-center gap-1.5 text-sm text-gray-400 hover:text-white transition-colors mb-6">
        ← Back to Leaderboard
      </Link>

      <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: May 29, 2026</p>

      <section className="mb-8 p-4 bg-violet-950/40 border border-violet-500/20 rounded-xl">
        <h2 className="text-base font-semibold text-white mb-2">TL;DR</h2>
        <p className="text-sm text-gray-300 leading-relaxed">
          This site does not use cookies, does not collect personal data, and does not track you.
          Match predictions are generated by AI models using publicly available information.
          No account or sign-up is required. The only external services involved are the AI APIs
          (Anthropic, OpenAI, Google, xAI), a live football data provider, and Ko-fi for optional
          donations — none of which receive any personal data from you as a visitor.
        </p>
      </section>

      <div className="space-y-8 text-sm text-gray-400 leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-white mb-3">1. Who is responsible</h2>
          <p>
            Vincent Will<br />
            <a href="https://vincentwill.com" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">
              vincentwill.com
            </a>
            {' · '}
            <a href="mailto:hello@vincentwill.com" className="text-violet-400 hover:underline">
              hello@vincentwill.com
            </a>
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">2. Data we collect</h2>

          <h3 className="font-semibold text-gray-200 mt-4 mb-1">Visitor data</h3>
          <p>
            We do not use analytics, tracking pixels, or cookies of any kind. Your visit to this
            site generates standard web server logs (IP address, timestamp, requested URL) that are
            retained for up to 7 days for operational purposes and then deleted. These logs are
            never shared with third parties.
          </p>

          <h3 className="font-semibold text-gray-200 mt-4 mb-1">AI predictions</h3>
          <p>
            Match predictions are generated server-side by calling AI APIs (Anthropic, OpenAI,
            Google DeepMind, xAI). These calls contain only match information (team names, date,
            stage) — no visitor data is ever included. Each provider's own privacy policy applies
            to the API requests we make:
          </p>
          <ul className="mt-2 ml-4 space-y-1 list-disc">
            <li><a href="https://www.anthropic.com/privacy" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">Anthropic Privacy Policy</a></li>
            <li><a href="https://openai.com/privacy" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">OpenAI Privacy Policy</a></li>
            <li><a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">Google Privacy Policy</a></li>
            <li><a href="https://x.ai/privacy-policy" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">xAI Privacy Policy</a></li>
          </ul>

          <h3 className="font-semibold text-gray-200 mt-4 mb-1">Live match data</h3>
          <p>
            Real-time scores and match data are fetched from{' '}
            <a href="https://www.football-data.org" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">
              football-data.org
            </a>{' '}
            server-side. No visitor data is sent.
          </p>

          <h3 className="font-semibold text-gray-200 mt-4 mb-1">Browser storage (localStorage)</h3>
          <p>
            Your browser stores one preference locally: whether you have dismissed the donation
            banner. This value never leaves your device and is not accessible to the server.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">3. Third-party services</h2>
          <p>
            Clicking the Ko-fi donation link takes you to{' '}
            <a href="https://ko-fi.com" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">ko-fi.com</a>,
            an independent platform with its own privacy policy. We have no access to any data you
            provide there. Ko-fi links are clearly marked and always open in a new tab.
          </p>
          <p className="mt-2">
            The fonts (Inter) are loaded from Google Fonts. Google may log the request.
            See{' '}
            <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">
              Google's Privacy Policy
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">4. Data sharing</h2>
          <p>
            We do not sell, rent, or share any data with third parties for marketing or advertising
            purposes. Server logs are not shared outside of operational necessity (e.g., hosting
            provider infrastructure).
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">5. Your rights</h2>
          <p>
            Under the GDPR you have the right to access, rectify, or request erasure of personal
            data held about you. Since we store no personal data beyond transient server logs, there
            is nothing to access or delete. If you have any concerns, please contact{' '}
            <a href="mailto:hello@vincentwill.com" className="text-violet-400 hover:underline">
              hello@vincentwill.com
            </a>.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">6. Changes to this policy</h2>
          <p>
            This policy may be updated occasionally. The date at the top of this page always
            reflects the most recent revision.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-white mb-3">7. Contact</h2>
          <p>
            Questions or requests:{' '}
            <a href="mailto:hello@vincentwill.com" className="text-violet-400 hover:underline">
              hello@vincentwill.com
            </a>
            {' '}or visit{' '}
            <a href="https://vincentwill.com" target="_blank" rel="noopener noreferrer" className="text-violet-400 hover:underline">
              vincentwill.com
            </a>.
          </p>
        </section>
      </div>
    </main>
  );
}
